export const Marker = {
    HEADER : "\\s",
    HEADER_1 : "\\s1",
    HEADER_2 : "\\s2",
    CROSS_REF : "\\r",
    DESCRIPTIVE_TITLE : "\\d",
    VERSE : "\\v" ,
    PARAGRAPH : "\\p",
    EMBEDDED_TEXT_OPENING : "\\pmo",
    BREAK : "\\b",
    CONTINUATION_PARAGRAPGH : "\\m",
    LIST_ENTRY : "\\li",
    LIST_ENTRY_1 : "\\li1",
    LIST_ENTRY_2 : "\\li2",
    LIST_ENTRY_3 : "\\li3",
    QUOTE : "\\q",
    QUOTE_1 : "\\q1",
    QUOTE_2 : "\\q2",
    QUOTE_3 : "\\q3",
    EPISTLE_OPEN : "\\po",
    CENTERED_PARAGRAPH : "\\pc",
    HEBREW_NOTE : "\\qd",
    QUOTE_RIGHT_ALIGNED : "\\qr",
}